%YAML:1.0
# data
# KITTI Dataset
dataset_dir: /home/jindong/SLAM/00

# camera intrinsics of graylevel camera left and right are same
# 00
camera.fx: 718.856
camera.fy: 607.1928
camera.cx: 718.856
camera.cy: 185.2157
camera.b:  0.5372

# 01
#camera.fx: 718.856
#camera.fy: 607.1928
#camera.cx: 718.856
#camera.cy: 185.2157
#camera.b:  0.5372

# 04
#camera.fx: 707.0912
#camera.fy: 601.8873
#camera.cx: 707.0912
#camera.cy: 183.1104
#camera.b:  0.5372

# VO Parameters
number_of_features: 500
scale_factor: 1.2
level_pyramid: 4
match_ratio: 2.0
max_num_lost: 10
min_inliers: 5
keyframe_rotation: 0.1
keyframe_translation: 0.1
map_point_erase_ratio: 0.1
